
spring:
  profiles:
    active: dev
server:
  port: 8088
#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.socket.domain
  mapperLocations: classpath:mapping/*.xml


---


#开发配置
spring:
  profiles: dev
  datasource:
      url: jdbc:mysql://localhost:3306/study_project?useOldAliasMetadataBehavior\=true&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
  devtools:
    restart:
      additional-paths: src/main/java
      enabled: true
    #freemarker热部署配置
  freemarker:
    cache: false
    template-loader-path: classpath:/templates/
    suffix: .ftl
    charset: utf-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    request-context-attribute: request
  resources:
    static-locations: classpath:/static/
